class Property {
  // AangebodenSinds
  final DateTime? offeredSince;

  // "AantalBadkamers": 1,
  final int? totalBedrooms;

  // "AantalKamers": 5,
  final int? totalRooms;

  // "Adres": "Cuijlenburg 52",
  final String? address;

  // "Bouwjaar": "2016",
  final String? constructionYear;

  // "Id": 6140616,
  final int? id;

  // HoofdFoto
  final String? mainPhotoUrl;

  // "VolledigeOmschrijving": "Ben je op zoek naar een instapklare, sfeervolle woning met een moderne uitstraling vlakbij het centrum van Boxmeer? Dan moet je de Cuijlenburg 52 komen bekijken! Deze verassend ruime tussenwoning is in 2016 gebouwd en is volledig geïsoleerd. Er is een gezellige open keuken met luxe inbouwapparatuur en een tuingerichte woonkamer. De zonnige tuin biedt veel privacy en heeft een houten fietsenschuur en een achterom. Op de eerste verdieping zijn 3 ruime slaapkamers en een modern ingerichte badkamer. Er is een vaste trap naar de tweede verdieping met grote raampartijen en een dakraam, waardoor je hier eenvoudig een extra slaapkamer kunt realiseren en er toch nog veel bergruimte beschikbaar blijft. Nieuwsgierig geworden? Maak dan snel een afspraak voor een bezichtiging van deze prachtige woning.\n\nBijzonderheden:\n-\tJonge woning uit 2016, instapklaar en in moderne lichte kleuren afgewerkt\n-\tVolledig geïsoleerd \n-\tEenvoudig vierde ruime slaapkamer te realiseren op de tweede verdieping\n-\tRustig gelegen nabij uitvalswegen en het gezellige centrum van Boxmeer\n-\tAltijd parkeerplaats beschikbaar voor de deur\n-\tDe slaapkamers aan de achterzijde van de woning hebben rolluiken\n-\tDe gehele woning is voorzien van een laminaatvloer (woonkamer nog geen 6 maanden oud)\n\nIndeling:\nBegane grond: hal, meterkast, toilet met fonteintje, open keuken met inbouwapparatuur zoals vaatwasser, koelkast, vriezer, combimagnetron, inductiekookplaat en afzuigkap. Woonkamer met provisiekast, uitzicht en toegang tot de tuin. \n\nVerdieping: overloop, 3 slaapkamers, moderne badkamer met inloopdouche, toilet en wastafelmeubel. \n\nZolder: vaste trap naar hoge open zolder met aansluitingen voor de wasmachine, CV-installatie en ventilatiesysteem.  Hier kun je eenvoudig een vierde ruime slaapkamer met dakraam realiseren. \n\nKenmerken:\nType woning: Tussenwoning met houten berging\nBouwjaar: 2016\nWoonoppervlakte: 140 m²\nExterne bergruimte: 6 m²\nInhoud woning: 535 m³\nPerceelgrootte: 136 m²\nAantal slaapkamers: 3 slaapkamers\nVerwarming en warm water: CV-installatie Intergas 2016, Duco ventilatiesysteem 2016\nElectra: Uitgebreide meterkast met ruim voldoende groepen en  aardlekschakelaars \nIsolatie: Geheel geïsoleerd\nEnergielabel: A\nGlasvezel aanwezig: ja",
  final String? completeDescription;

  // "KoopPrijs": 325000,
  final int? sellPrice;

  Property({
    required this.offeredSince,
    required this.totalBedrooms,
    required this.totalRooms,
    required this.address,
    required this.constructionYear,
    required this.id,
    required this.mainPhotoUrl,
    required this.completeDescription,
    required this.sellPrice,
  });

  static Property fromJson(Map<String, dynamic> json) => Property(
        // offeredSince: json['AangebodenSinds'] as String,
        offeredSince: null,
        totalBedrooms: json['AantalBadkamers'] as int?,
        totalRooms: json['AantalKamers'] as int?,
        address: json['Adres'] as String?,
        constructionYear: json['Bouwjaar'] as String?,
        id: json['id'] as int?,
        mainPhotoUrl: json['HoofdFoto'] as String?,
        completeDescription: json['VolledigeOmschrijving'] as String?,
        sellPrice: json['sellPrice'] as int?,
      );

// "WGS84_X": 5.94154644,
// "WGS84_Y": 51.6535759,

}

// {
// "AangebodenSinds": "/Date(1635255041000+0200)/",
// "AangebodenSindsTekst": "vandaag",
// "AantalBadkamers": 1,
// "AantalKamers": 5,
// "AantalSlaapkamers": null,
// "AantalWoonlagen": "2 woonlagen en een zolder",
// "Aanvaarding": "In overleg",
// "Adres": "Cuijlenburg 52",
// "AfgekochtDatum": null,
// "BalkonDakterras": null,
// "BedrijfsruimteCombinatieObject": null,
// "BezichtingDagdelen": [],
// "BezichtingDagen": [],
// "BijdrageVVE": null,
// "Bijzonderheden": null,
// "Bouwjaar": "2016",
// "Bouwvorm": "bestaande bouw",
// "BronCode": "NVM",
// "ContactpersoonEmail": null,
// "ContactpersoonTelefoon": null,
// "Cv": "Intergas (gas gestookt combiketel uit 2016, Eigendom)",
// "DatumOndertekeningAkte": null,
// "Deeplink": null,
// "DetailInfo": {},
// "EigendomsSituatie": null,
// "Energielabel": {},
// "ErfpachtBedrag": null,
// "Garage": null,
// "GarageIsolatie": null,
// "GarageVoorzieningen": null,
// "GelegenOp": null,
// "GewijzigdDatum": "/Date(1635255041000+0200)/",
// "HoofdFoto": "http://cloud.funda.nl/valentina_media/151/076/058_groot.jpg",
// "HoofdFotoSecure": "http://cloud.funda.nl/valentina_media/151/076/058_groot.jpg",
// "HoofdTuinType": "achtertuin",
// "Id": 6140616,
// "IndBasisPlaatsing": true,
// "IndFotos": true,
// "IndIpix": true,
// "IndOpenhuizenTopper": false,
// "IndPDF": true,
// "IndPlattegrond": true,
// "IndTop": false,
// "IndVeilingProduct": false,
// "IndVideo": true,
// "Inhoud": 535,
// "InternalId": "092cc8ac-5e12-4654-8fed-1bcfe802771d",
// "IsIngetrokken": false,
// "IsVerhuurd": false,
// "IsVerkocht": false,
// "Isolatie": "volledig geïsoleerd",
// "Kenmerken": [],
// "KenmerkenKort": {},
// "KenmerkenTitel": null,
// "Ligging": "aan rustige weg en in woonwijk",
// "MLIUrl": "https://www.knab.nl/hypotheken/funda/index.html?price=325000&zip=5831TM&hsnr=52",
// "Makelaar": "EEF Makelaars",
// "MakelaarId": 13184,
// "MakelaarTelefoon": "0485745758",
// "MedeAanbieders": [],
// "Media": [],
// "Media-Foto": [],
// "MobileURL": "https://m.funda.nl/koop/boxmeer/huis-42595079-cuijlenburg-52/",
// "ObjectType": "woonhuis",
// "ObjectTypeMetVoorvoegsel": "deze woning",
// "OpenHuizen": [],
// "PerceelOppervlakte": 136,
// "PermanenteBewoning": "permanente bewoning is toegestaan",
// "Plaats": "Boxmeer",
// "Postcode": "5831TM",
// "Prijs": {},
// "PrijsGeformatteerd": "<span class=\"price-wrapper\"><span class=\"price\">&euro;&nbsp;325.000</span> <abbr class=\"price-ext\">k.k.</abbr></span>",
// "Project": null,
// "ProjectNaam": null,
// "PublicatieDatum": "/Date(1635255041000+0200)/",
// "PublicatieStatus": 0,
// "SchuurBerging": "vrijstaande houten berging",
// "SchuurBergingIsolatie": null,
// "SchuurBergingVoorzieningen": "elektra",
// "ScrambledId": "42595079",
// "ServiceKosten": 0,
// "SoortAanbod": 10,
// "SoortDak": "zadeldak bedekt met dakpannen",
// "SoortGarage": "eengezinswoning, tussenwoning",
// "SoortParkeergelegenheid": "eengezinswoning, tussenwoning",
// "SoortPlaatsing": 0,
// "SoortWoning": "eengezinswoning, tussenwoning",
// "Titels": [],
// "ToonBezichtigingMaken": true,
// "ToonBrochureAanvraag": true,
// "ToonMakelaarWoningaanbod": true,
// "ToonReageren": true,
// "TransactieAfmeldDatum": null,
// "TransactieMakelaarId": null,
// "TransactieMakelaarNaam": null,
// "TuinLigging": "gelegen op het zuiden bereikbaar via achterom",
// "TypeProject": 0,
// "URL": "http://www.funda.nl/koop/boxmeer/huis-42595079-cuijlenburg-52/",
// "Veiling": {},
// "VerkoopStatus": "Beschikbaar",
// "Verwarming": "C.V.-ketel",
// "Video": {},
// "VolledigeOmschrijving": "Ben je op zoek naar een instapklare, sfeervolle woning met een moderne uitstraling vlakbij het centrum van Boxmeer? Dan moet je de Cuijlenburg 52 komen bekijken! Deze verassend ruime tussenwoning is in 2016 gebouwd en is volledig geïsoleerd. Er is een gezellige open keuken met luxe inbouwapparatuur en een tuingerichte woonkamer. De zonnige tuin biedt veel privacy en heeft een houten fietsenschuur en een achterom. Op de eerste verdieping zijn 3 ruime slaapkamers en een modern ingerichte badkamer. Er is een vaste trap naar de tweede verdieping met grote raampartijen en een dakraam, waardoor je hier eenvoudig een extra slaapkamer kunt realiseren en er toch nog veel bergruimte beschikbaar blijft. Nieuwsgierig geworden? Maak dan snel een afspraak voor een bezichtiging van deze prachtige woning.\n\nBijzonderheden:\n-\tJonge woning uit 2016, instapklaar en in moderne lichte kleuren afgewerkt\n-\tVolledig geïsoleerd \n-\tEenvoudig vierde ruime slaapkamer te realiseren op de tweede verdieping\n-\tRustig gelegen nabij uitvalswegen en het gezellige centrum van Boxmeer\n-\tAltijd parkeerplaats beschikbaar voor de deur\n-\tDe slaapkamers aan de achterzijde van de woning hebben rolluiken\n-\tDe gehele woning is voorzien van een laminaatvloer (woonkamer nog geen 6 maanden oud)\n\nIndeling:\nBegane grond: hal, meterkast, toilet met fonteintje, open keuken met inbouwapparatuur zoals vaatwasser, koelkast, vriezer, combimagnetron, inductiekookplaat en afzuigkap. Woonkamer met provisiekast, uitzicht en toegang tot de tuin. \n\nVerdieping: overloop, 3 slaapkamers, moderne badkamer met inloopdouche, toilet en wastafelmeubel. \n\nZolder: vaste trap naar hoge open zolder met aansluitingen voor de wasmachine, CV-installatie en ventilatiesysteem.  Hier kun je eenvoudig een vierde ruime slaapkamer met dakraam realiseren. \n\nKenmerken:\nType woning: Tussenwoning met houten berging\nBouwjaar: 2016\nWoonoppervlakte: 140 m²\nExterne bergruimte: 6 m²\nInhoud woning: 535 m³\nPerceelgrootte: 136 m²\nAantal slaapkamers: 3 slaapkamers\nVerwarming en warm water: CV-installatie Intergas 2016, Duco ventilatiesysteem 2016\nElectra: Uitgebreide meterkast met ruim voldoende groepen en  aardlekschakelaars \nIsolatie: Geheel geïsoleerd\nEnergielabel: A\nGlasvezel aanwezig: ja",
// "Voorzieningen": "<{balansventilatie}>, buitenzonwering, dakraam, glasvezelkabel en rolluiken",
// "WGS84_X": 5.94154644,
// "WGS84_Y": 51.6535759,
// "WarmWater": "C.V.-ketel",
// "WoonOppervlakte": 140,
// "EersteHuurPrijs": null,
// "EersteHuurPrijsLang": null,
// "EersteKoopPrijs": null,
// "EersteKoopPrijsLang": null,
// "HuurPrijs": null,
// "HuurPrijsLang": null,
// "HuurPrijsTot": null,
// "Huurprijs": null,
// "HuurprijsFormaat": null,
// "KoopPrijs": 325000,
// "KoopPrijsLang": "<[KoopPrijs]> <{kosten koper|lang}>",
// "Koopprijs": 325000,
// "KoopprijsFormaat": "<[KoopPrijs]> <{kosten koper|kort}>",
// "KoopprijsTot": null,
// "ShortURL": "http://funda.nl/42595079",
// "Tuin": "achtertuin",
// "VeilingGeformatteerd": null
// }
