name: funda
description: Funda flutter assignment
publish_to: none

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # core
  intl: ^0.17.0
  logging: ^1.0.1

  # architecture
  get_it: ^7.2.0
  bloc: ^7.2.1
  flutter_bloc: ^7.3.1
  either_option: ^2.0.0

  # networking
  dio: ^4.0.1
  dio_logger: ^4.0.8+8

dev_dependencies:
  flutter_test:
    sdk: flutter

  mocktail: ^0.1.4
  bloc_test: ^8.3.0

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true